name: tavern
version: 0.0.7
homepage: https://github.com/tapted/tavern
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  archive: '>=1.0.16'
  chrome: any
  collection_helpers: any
  path: any
  range: any
  stack_trace: any
  yaml: any
